apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-retain
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-retain

