apiVersion: v1
kind: Pod
metadata:
  name: jupyterlab
  labels:
    app: jupyterlab
spec:
  serviceAccountName: spark-driver
  securityContext:
    fsGroup: 777
  imagePullSecrets:
  - name: "dockerhub"
  containers:
  - name: jupyter-driver-pod
    image: dockerhub.dsc.com.vn/dsc_datawarehouse/jupyterlab:spark-k8s-jupyter
    imagePullPolicy: Always
    command: ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    volumeMounts:
    - name: notebook-data
      mountPath: /opt/spark/work-dir/
  volumes:
    - name: notebook-data
      persistentVolumeClaim:
        claimName: jupyterlab

  restartPolicy: Always
