apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlab
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-retain
  nfs:
    path: /mnt/nfs-share/jupyterlab/
    server: 10.32.1.100
