apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-retain
  nfs:
    path: /mnt/nfs-share/minio/data-2/
    server: 10.32.1.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-2
  namespace: datalake
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-retain
